### ISSUE TITLE
Make the window go away after a specified period…

### ISSUE THREAD

**Issue by Hamzabdx** [ugly-soul/VolumeManager#4]
Make the window go away after a specified period for example 5 seconds Also make it so we can resize it and change location of the tweak also make it so the tweak doesnt work when the screen is locked bcz of always on display thanks

**Comment by ugly-soul** [comment]
ok，有时间的时候会更新以支持这个优化项。

**Comment by ugly-soul** [comment]
> 让窗口在指定的时间（例如 5 秒）后消失，还可以调整其大小并更改调整的位置，还可以使调整在屏幕锁定时不起作用，因为始终显示，谢谢

好的，有时间的时候会更新以支持这个优化项。

**Comment by Hamzabdx** [comment]
Ok i appreciate it bro

**Comment by ugly-soul** [comment]
自己编译源码，已支持这个功能。
